spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:phoenix:192.168.230.130:2181;phoenix.schema.isNamespaceMappingEnabled=true
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    encoding: UTF-8 #编码
#    suffix: .html #模板后缀
#    mode: HTML #模板
mybatis:
  configuration:
    map-underscore-to-camel-case: true